### ISSUE TITLE
Output changes metabug

### ISSUE THREAD

**Issue by ogham** [ogham/exa#90]
I’ve tried to get through some of the older, more simple bugs, and I’ve been running into problems caused by poorly-factored code that I wrote earlier this year:
- Any instance of coloured text is _immediately_ converted to a `String` with ANSI escape codes, meaning that not only does it allocate too soon, but it ties us to that particular style of terminal;
- The implementations for the ‘grid’, ‘grid_details’, ‘details’, and ‘tree’ views are woefully intertwined, with the ‘details’ view doing almost all the work in all cases;
- The `Table` struct in the ‘details’ view contains both fields that specify how output cells should be formatted _and_ fields that the output is collected into.

To clarify what I mean by those outputs being all intermingled: some of the structs now have so many fields that it’s possible to construct invalid instances of these types where two fields can conflict. For example, the ‘grid_details’ output has _two_ `Colours` fields to choose from: one in `grid`, and another in `details`. Which one it picks is arbitrary, but I’d like to not have to worry about picking one at all. Similarly, it makes no sense for the ‘grid_details’ view to have tree-structure characters in it (how would you display that in a grid?), and this has to be checked for manually rather than just making instances of that type of output forbidden by the type system somehow. Whew, I hope all this makes sense.
### Output changes checklist

So, in the [develop](https://github.com/ogham/exa/tree/develop) branch, I plan to do the following:
- [x] Refactor any instances where coloured text is produced so that it is converted to an owned, escape-coded `String` at the last possible moment. This is now possible thanks to recent changes to the `ansi_term` crate (ogham/rust-ansi-term@446e985fa85609ceb0ce1da96cbb544076ec29e2) that makes `ANSIStrings` copy-on-write instead of borrowed.
- [x] Separate the code that creates the tree structure cells from the code that creates the file details cells. This only recently became possible with the ability to display a tree without its details.
- [x] Separate the code that builds a Table from the fields that specify how a table is created. (Right now they are both the `Table` struct)
- [x] Add a new type, ‘permissions and extended attribute flag’, that simplifies the rendering code so that the ‘does this file have extended attributes?’ flag doesn’t have to be passed to _every_ rendering function.
- [ ] Replace the tree view with a streaming output (see #82). Without there being a table involved, this can now be done.
- [x] Replace any values that are used in an entire table to be `lazy_static` globals (right now these are just the users cache and the current year).
- [x] Replace any calls to `print!` or `println!` with a call to `write!` or `writeln!` with an output handle.
- [ ] Try to find a way to print onto other types of terminal (see #52 and, ultimately, #32)

This also paves the way for structured output (see #13).

From here, exa should have a more stable codebase that I can get around to fixing some of the actual bugs!

**Comment by petevine** [comment]
> Any instance of coloured text is immediately converted to a String 

Is this the reason I'm getting this crash on x86 Linux?

````
bash-4.3$  target/release/exa -l

Program received signal SIGSEGV, Segmentation fault.
0xb7ba8e77 in pthread_mutex_lock () from /lib/libpthread.so.0
(gdb) bt
#0  0xb7ba8e77 in pthread_mutex_lock () from /lib/libpthread.so.0
#1  0xb7f1d4f2 in pthread_mutex_lock () from /lib/libc.so.6
#2  0x800ccf67 in je_malloc_mutex_lock () at /mnt/home/petevine/unpacked/rustc-nightly/src/jemalloc/include/jemalloc/internal/mutex.h:77
#3  je_arena_dalloc_large () at /mnt/home/petevine/unpacked/rustc-nightly/src/jemalloc/src/arena.c:1868
#4  0x800c6972 in je_arena_sdalloc () at /mnt/home/petevine/unpacked/rustc-nightly/src/jemalloc/include/jemalloc/internal/arena.h:1203
#5  je_isdalloct () at include/jemalloc/internal/jemalloc_internal.h:784
#6  je_isqalloc () at include/jemalloc/internal/jemalloc_internal.h:813
#7  isfree () at /mnt/home/petevine/unpacked/rustc-nightly/src/jemalloc/src/jemalloc.c:1257
#8  je_sdallocx () at /mnt/home/petevine/unpacked/rustc-nightly/src/jemalloc/src/jemalloc.c:1896
#9  0x8005db74 in std..ffi..c_str..CString::drop.10126::h1cd698869c39c3af ()
#10 0x8011a938 in ?? ()
````

The `-l` option is mandatory to trigger.

**Comment by petevine** [comment]
Sorry, I think I must have accidentally used a broken rustc :) I'll delete these entries in a moment.

**Comment by ogham** [comment]
One day, one day.

**Comment by ogham** [comment]
And that day is today! Y’know, three days after I was meant to release 0.7.0. But time, as they say, is relative. I don’t know what that means, but it sounds smart.

Let’s look at what’s *not* done first: the checkbox at the end for printing onto non-VT102-compatible terminals, and one near the middle for streaming the tree view. [ansi-term](https://github.com/ogham/rust-ansi-term) remains true to its name, and doesn’t support reading termcap entries or anything like that, so this is still a no-go. (Though its issue will remain open.) Streaming view ultimately proved difficult as well; while we can `stat` and display files one-by-one, we can’t print anything until they’re all *sorted*, and even the deepest tree will need to be displayed in alphabetical order.

To its credit, though, that merge did bring some streaming-related performance improvements with it. When in details view, exa will now print lines as they’re formatted, rather than filling up a buffer and only printing anything once it’s full: it won’t make exa significantly faster, but it’ll display the first line a bit quicker.

Improvements to the code meant that the “table” part of the details view was separated from the “tree and filename” part, and you can now have one without the other. This also speeds up the tree view, as it no longer has to ask the computer for information it won’t even end up using (time zone, locale formatting info, etc). And for what it’s worth, it makes the code much nicer to edit, with less risk of breakage.

So I think this is as far as exa’s first and only metabug is going to get!
